services:
  - type: web
    name: treewalley-furniture
    env: node
    plan: free
    buildCommand: npm ci
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: ADMIN_KEY
        sync: false
